version: '3'
services:
  workflows_viewer:
    build: ./camunda-scada-lts-workflow-viewer
    image: registry.csec.dibris.unige.it:5000/fdt-camunda-workflow-viewer
    networks:
      a25_ind_enterprise:
        ipv4_address: 172.16.10.101
      zzz999_management:
        ipv4_address: 10.0.0.23
    environment:
      SCADALTS_URL: http://scada:8080/ScadaLTS