version: '3'
services:
  docker_api_proxy:
    build: ./docker-api-proxy
    image: gabibbo97/lidite-docker-api-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      a25_ind_enterprise:
        ipv4_address: 172.16.10.102
      zzz999_management:
        ipv4_address: 10.0.0.5
