version: '3'
services:
  # Cabinet
  cabinet_biblioteca:
    build: ./cabinet
    image: gabibbo97/lidite-cabinet
    environment:
     - "ID=biblioteca"
     - "BASE=1560"
     - "MAXLOAD=7500"
     - "VERBOSE=1"
     - "URL=tcp://docker_api_proxy:1337"
    depends_on:
      - docker_api_proxy
    restart: on-failure
    networks:
      a30_industrial:
       ipv4_address: 10.10.10.55
      zzz999_management:
        ipv4_address: 10.0.0.55

  plc_biblioteca:
    build: ./openplc
    image: gabibbo97/lidite-openplc
    volumes:
    - ./config/openplc/trip.st:/data/main.st:ro
    - ./config/openplc/modbus-slaves/cabinet-biblioteca.cfg:/data/mbconfig.cfg:ro
    networks:
      a30_industrial:
       ipv4_address: 10.10.10.65
      zzz999_management:
       ipv4_address: 10.0.0.65

  # Clients
  client_biblioteca:
    build: ./nothing
    image: gabibbo97/lidite-nothing
    scale: 1
    network_mode: none
    labels:
      fdt.cabinetID: biblioteca
      fdt.minload: 240
      fdt.maxload: 260