version: '3'
services:
  # Cabinet
  cabinet_lagorio:
    build: ./cabinet
    image: gabibbo97/lidite-cabinet
    environment:
     - "ID=lagorio"
     - "BASE=1560"
     - "MAXLOAD=7500"
     - "VERBOSE=1"
     - "URL=tcp://docker_api_proxy:1337"
    depends_on:
      - docker_api_proxy
    restart: on-failure
    networks:
      a30_industrial:
       ipv4_address: 10.10.10.51
      zzz999_management:
       ipv4_address: 10.0.0.51
  plc_lagorio:
    build: ./openplc
    image: gabibbo97/lidite-openplc
    volumes:
    - ./config/openplc/trip.st:/data/main.st:ro
    - ./config/openplc/modbus-slaves/cabinet-lagorio.cfg:/data/mbconfig.cfg:ro
    networks:
      a30_industrial:
       ipv4_address: 10.10.10.61
      zzz999_management:
       ipv4_address: 10.0.0.61
  # Clients
  client_lagorio:
    build: ./nothing
    image: gabibbo97/lidite-nothing
    scale: 1
    network_mode: none
    labels:
      fdt.cabinetID: lagorio
      fdt.minload: 240
      fdt.maxload: 260