version: '3'
services:
  # Cabinet
  cabinet_delfino:
    build: ./cabinet
    image: gabibbo97/lidite-cabinet
    environment:
     - "ID=delfino"
     - "BASE=1560"
     - "MAXLOAD=7500"
     - "VERBOSE=1"
     - "URL=tcp://docker_api_proxy:1337"
    depends_on:
      - docker_api_proxy
    restart: on-failure
    networks:
      a30_industrial:
       ipv4_address: 10.10.10.50
      zzz999_management:
       ipv4_address: 10.0.0.50
  plc_delfino:
    build: ./openplc
    image: gabibbo97/lidite-openplc
    volumes:
    - ./config/openplc/trip.st:/data/main.st:ro
    - ./config/openplc/modbus-slaves/cabinet-delfino.cfg:/data/mbconfig.cfg:ro
    networks:
      a30_industrial:
       ipv4_address: 10.10.10.60
      zzz999_management:
       ipv4_address: 10.0.0.60
  # Clients
  client_delfino:
    build: ./nothing
    image: gabibbo97/lidite-nothing
    scale: 1
    network_mode: none
    labels:
      fdt.cabinetID: delfino
      fdt.minload: 240
      fdt.maxload: 260
