version: '3'
services:
  website:
    image: nginx:1.19.10
    volumes:
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      zzz999_management: {} # The proxy download does not belong to the scenario traffic
      z95_dmz:
        ipv4_address: 192.168.100.80