version: '3'
services:
  # Cabinet
  cabinet_seb:
    build: ./cabinet
    image: gabibbo97/lidite-cabinet
    environment:
     - "ID=seb"
     - "BASE=1560"
     - "MAXLOAD=7500"
     - "VERBOSE=1"
     - "URL=tcp://docker_api_proxy:1337"
    depends_on:
      - docker_api_proxy
    restart: on-failure
    networks:
      a30_industrial:
        ipv4_address: 10.10.10.54
      zzz999_management:
       ipv4_address: 10.0.0.54
  plc_seb:
    build: ./openplc
    image: gabibbo97/lidite-openplc
    volumes:
    - ./config/openplc/trip.st:/data/main.st:ro
    - ./config/openplc/modbus-slaves/cabinet-seb.cfg:/data/mbconfig.cfg:ro
    networks:
      a30_industrial:
       ipv4_address: 10.10.10.64
      zzz999_management:
       ipv4_address: 10.0.0.64
  # Client
  client_seb:
    build: ./nothing
    image: gabibbo97/lidite-nothing
    scale: 1
    network_mode: none
    labels:
      fdt.cabinetID: seb
      fdt.minload: 240
      fdt.maxload: 260