global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - 127.0.0.1:9090
- job_name: node-exporter
  static_configs:
  - targets:
    - 127.0.0.1:9100
- job_name: cadvisor
  static_configs:
  - targets:
    - 127.0.0.1:9101
- job_name: docker
  static_configs:
  - targets:
    - 127.0.0.1:9323
